---
title: "HW3"
author: "Lucy Gagnon"
format: pdf
editor: visual
---

## Question 2

*The Uniform-Pareto*\
**The goal of this problem is to continue getting more practice calculating the posterior distribution.**\

Suppose $a < x < b.$ Consider the notation $I_{(a,b)}(x),$ where $I$ denotes the indicator function. We define $I_{(a,b)}(x)$ to be the following:

$$
I_{(a,b)}(x)=
\begin{cases} 
1 & \text{if $a < x < b$,}
\\
0 &\text{otherwise.}
\end{cases}
$$

Let X be a random variable and let x be an observed value. Let

$$
\begin{aligned}
X=x \mid \theta &\sim \text{Uniform}(0,\theta)\\
\theta &\sim \text{Pareto}(\alpha,\beta),
\end{aligned}
$$

where $p(\theta) = \dfrac{\alpha\beta^\alpha}{\theta^{\alpha+1}}I_{(\beta,\infty)}(\theta).$ Write out the likelihood $p(X=x\mid \theta).$

Then calculate the posterior distribution of $\theta|X=x.$

$\textbf{Hint 1}$: To set up this problem, do the following:

$$p(\theta \mid x) \propto \frac{1}{\theta} I_{(0,\theta)}(x)
\times 
\frac{\alpha \beta^{\alpha}}
{\theta^{\alpha + 1}}
I_{(\beta, \infty)}(\theta).$$

$\textbf{Hint 2}$: You cannot drop the indicators. You must write the indicators as functions of $\theta$ since this is the random variable.

$\textbf{Hint 3}$: It will end up being an updated Pareto.

\_\_\_\_\_\_\_\_

*Proof.* Consider the notation $I_{(a,b)}(x),$ where $I$ denotes the indicator function. We define $I_{(a,b)}(x)$ to be the following:

$$
I_{(a,b)}(x)=
\begin{cases} 
1 & \text{if $a < x < b$,}
\\
0 &\text{otherwise.}
\end{cases}
$$

Let *X* be a random variable and let *x* be an observed value. Let

$$
\begin{aligned}
X=x \mid \theta &\sim \text{Uniform}(0,\theta)\\
\theta &\sim \text{Pareto}(\alpha,\beta),
\end{aligned}
$$

where $p(\theta) = \dfrac{\alpha\beta^\alpha}{\theta^{\alpha+1}}I_{(\beta,\infty)}(\theta).$ The likelihood $p(X=x\mid \theta)$ may be written as

$$
p(X=x\mid \theta) = \left( \frac {1}{\theta - 0} \right) * \mathbf{I}_{(0, \theta)}(x) = \left( \frac {1}{\theta} \right) * \mathbf{I}_{(0, \theta)}(x).
$$

We will calculate the posterior distribution of $\theta|X=x.$ By Bayes' Theorem, observe

$$
p(\theta \mid x) = \frac{p(x, \theta)}{p(x)} = \frac{p(x \mid \theta) * p(\theta)}{p(x)} \propto p(x \mid \theta) * p(\theta).
$$

when we absorb terms that do not depend on $\theta$ ( i.e., $p(x)$) into the constant of proportionality. Substituting in our likelihood and prior gives

$$
\begin{aligned}
p(x \mid \theta) *p(\theta) \\&=
\left( \left( \frac {1}{\theta} \right) * \mathbf{I}_{(0, \theta)}(x) \right) * \left( \dfrac{\alpha\beta^\alpha}{\theta^{\alpha+1}}I_{(\beta,\infty)}(\theta) \right) \\ &\propto  
\mathbf{I}_{(0, \theta)}(x) \frac{1}{\theta^{(\alpha+1)+1}}I_{(\beta,\infty)}(\theta) .
\end{aligned}
$$

When we absorb terms not depending on $\theta$ into the constant of proportionality. To simplify the indicator functions into 1 term, we must consider the region where both

$$
\mathbf{I}_{(0, \theta)}(x) = 1 
$$

and

$$
\mathbf{I}_{(\beta, \infty)}(\theta) = 1,
$$

which is true for $x<\theta$. Thus, we have

$$
\mathbf{I}_{(0, \theta)}(x) \frac{1}{\theta^{(\alpha+1)+1}}I_{(\beta,\infty)}(\theta) = \frac{1}{\theta^{(\alpha+1)+1}}I_{(\max(\beta,x),\infty)}(\theta) \propto \text{Pareto}(\alpha' = \alpha+1, \beta' = \max(\beta,x)). 
$$

Therefore, the posterior distribution of of $\theta|X=x$ is and updated Pareto distribution,

$$
\theta\mid X=x \sim \text{Pareto}(\alpha' = \alpha+1, \beta' = \max(\beta,x)). 
$$

## *Question 3*

*The Bayes estimator or Bayes rule*\
**The goal of this problem is to practice a similar problem that we considered in Module 2, where we derived the Bayes rule under squared error loss and found the result was the posterior mean.**

### Part A

Find the Bayes estimator (or Bayes rule) when the loss function is $L(\theta, \delta(x))~=~c~(\theta-\delta(x))^2,$ where $c >0$ is a constant.

*Proof.* Suppose we have the loss function $L(\theta, \delta(x))~=~c~(\theta-\delta(x))^2,$ where $c >0$ is a constant. We will find the Bayes estimator, $\hat{\delta}(x)$. Observe

$$
\begin{aligned}
\rho(\theta,\delta(x)) &=  E[L(\theta,\delta(x))|X] \\
&=E[c(\theta-\delta(x))^2\mid X]\\
&=E[c(\theta^2-2\theta\delta(x)-\delta(x)^2)\mid X]\\
&=c(E[\theta^2\mid X]-2\delta(x)E[\theta\mid X]+\delta(x)^2).
\end{aligned}
$$

To find the Bayes estimator, we take the derivative with respect to $\delta(x)$

$$
\frac{\partial \rho(\theta, \delta(x))}{\partial \delta(x)}=c(-2E[\theta\mid X]+2\delta(x))
$$

and solve for $\hat{\delta}(x)$ when $\frac{\partial \rho(\theta, \delta(x))}{\partial \delta(x)}=0$. Observe

$$
0 =c(-2E[\theta\mid X]+2\hat{\delta}(x)).
$$

Solving for $\hat{\delta}(x)$ gives $\hat{\delta}(x) = E[\theta \mid X]$. To check if the solution is unique, it must be true that $\frac{\partial^2 \rho(\theta, \delta(x))}{\partial \delta(x)^2} >0.$ Here, we find

$$
\frac{\partial^2 \rho(\theta, \delta(x))}{\partial \delta(x)^2} = 2c>0.
$$

since $c>0$. Thus, our Bayes estimator is unique. QED

### Part B

Derive the Bayes estimator (or Bayes rule) when $L(\theta, \delta(x)) = w(\theta) (g(\theta)-\delta(x))^2.$ Assume that $w(\theta) > 0.$

Hint: Do so without writing any integrals. Note that you can write $\rho(\theta,\delta(x)) =  E[L(\theta,\delta(x))|X].$ Don't forget to prove or state why the Bayes rule(s) are unique.

*Proof.* Suppose we have the loss function $L(\theta, \delta(x))~=w(\theta)(g(\theta)-\delta(x))^2,$ where $w(\theta) >0$ is a constant. We will find the Bayes estimator, $\hat{\delta}(x)$. Observe

$$
\begin{aligned}
\rho(\theta,\delta(x)) &=  E[L(\theta,\delta(x))|X] \\
&=E[w(\theta)(g(\theta)-\delta(x))^2 \mid X]\\
&=E[w(\theta)(g(\theta)^2-2g(\theta)\delta(x)-\delta(x)^2)\mid X]\\
&=E[w(\theta)g(\theta)^2\mid X]-2\delta(x)E[w(\theta)g(\theta)\mid X]+\delta(x)^2E[w(\theta)\mid X]).
\end{aligned}
$$

To find the Bayes estimator, we take the derivative with respect to $\delta(x)$,

$$
\frac{\partial \rho(\theta, \delta(x))}{\partial \delta(x)}=-2E[w(\theta)g(\theta)\mid X]+2\delta(x)E[w(\theta)\mid X])
$$

and solve for $\hat{\delta}(x)$ when $\frac{\partial \rho(\theta, \delta(x))}{\partial \delta(x)}=0$. Observe

$$
0=-2E[w(\theta)g(\theta)\mid X]+2\hat{\delta}(x)E[w(\theta)\mid X]).
$$

Solving for $\hat{\delta}(x)$ gives $\hat{\delta}(x) = \frac{E[w(\theta)g(\theta) \mid X]}{E[w(\theta) \mid X]}$. To check if the solution is unique, it must be true that $\frac{\partial^2 \rho(\theta, \delta(x))}{\partial \delta(x)^2} >0.$ Here, we find

$$
\frac{\partial^2 \rho(\theta, \delta(x))}{\partial \delta(x)^2} = 2*E[w(\theta)\mid X]>0.
$$

since we assume $w(\theta)>0$. Thus, our Bayes estimator is unique. QED
